name = "pink"
version = "1.0.0"
target = "javascript"

description = "Bindings to Ink. A library for building terminal UIs."
licences = ["Apache-2.0"]
repository = { type = "github", user = "Massolari", repo = "pink" }
links = [{ title = "Ink", href = "https://github.com/vadimdemedes/ink" }]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.1.6 and < 2.0.0"
gleam_javascript = ">= 0.12.0 and < 1.0.0"
