name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 9
      - uses: erlef/setup-beam@v1
        with:
          otp-version: false
          gleam-version: "1.16.0"
      - run: pnpm install
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
